services:
  backend:
    build:
      context: ./backend
    container_name: renewable-backend
    ports:
      - "8000:8000"
    volumes:
      - renewable_data:/app/data

  frontend:
    build:
      context: ./frontend
    container_name: renewable-frontend
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  renewable_data:
